/**
 * AI-Powered Recommendations Component
 */

import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { Bot, RefreshCw } from 'lucide-react';
import { generateGeminiResponse } from '../services/gemini';
import './RecommendationsCard.css';

export const RecommendationsCard = ({ instance = null, analysis = null, loading = false }) => {
  const [aiRecommendation, setAiRecommendation] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [error, setError] = useState(null);

  // Use an effect to fetch actual AI recommendations when the instance changes
  useEffect(() => {
    let mounted = true;

    const fetchAIRecommendations = async () => {
      if (!instance || !instance.id) return;

      const cacheKey = `gemini_cache_instance_${instance.id}`;
      const cachedData = sessionStorage.getItem(cacheKey);

      if (cachedData) {
        setAiRecommendation(cachedData);
        return;
      }

      setAiLoading(true);
      setError(null);

      try {
        const prompt = `Please act as a Cloud Cost Optimization FinOps AI. Analyze this specific instance based on real-time metrics. Provide 3 highly specific, clear, actionable recommendations (in markdown bullet points) to optimize its costs and performance. Be concise.`;

        const resp = await generateGeminiResponse(prompt, instance);

        if (mounted) {
          setAiRecommendation(resp);
          sessionStorage.setItem(cacheKey, resp);
        }
      } catch (err) {
        if (mounted) {
          const errMsg = err.message || '';
          if (errMsg.includes('429') || errMsg.includes('Quota exceeded')) {
            setError("Google Gemini Free Tier limit reached. Serving latest rule-based insights below instead.");
            // Fallback to rule-based analysis if available
            if (analysis && analysis.recommendations) {
              const ruleBasedFallback = analysis.recommendations.map(r => `* **${r.action}**: ${r.reason} (Savings: $${r.savings.toFixed(2)})`).join('\n\n');
              setAiRecommendation(`### Fallback: Rule-Based Recommendations\n\n${ruleBasedFallback}`);
            }
          } else {
            setError("Failed to fetch AI recommendations. Please try again later.");
          }
          console.warn("Gemini API Error handled gracefully:", err);
        }
      } finally {
        if (mounted) {
          setAiLoading(false);
        }
      }
    };

    fetchAIRecommendations();

    return () => {
      mounted = false;
    };
  }, [instance?.id]); // Only re-fetch when instance ID changes to save API calls

  if (loading && !aiRecommendation) {
    return (
      <div>
        <h3 className="text-lg font-semibold mb-4">💡 AI Recommendations</h3>
        <div className="flex items-center justify-center h-[200px]">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h3 className="recommendation-header-title">
          <Bot className="recommendation-bot-icon" />
          True AI Recommendations
        </h3>
        {aiLoading && (
          <div className="recommendation-loading-badge">
            <RefreshCw size={14} className="animate-spin" />
            Generating Insights...
          </div>
        )}
      </div>

      {/* Dynamic AI Analysis Generated by Gemini */}
      <div className="ai-recommendation-content">
        {aiLoading && !aiRecommendation ? (
          <div className="flex flex-col items-center justify-center h-full gap-4">
            <div className="animate-pulse flex items-center gap-3 text-purple-400">
              <Bot size={32} className="animate-bounce" />
              <span className="font-semibold text-lg">NeuroNest is Thinking...</span>
            </div>
          </div>
        ) : error ? (
          <div className="text-red-500 text-sm flex items-center gap-2 p-4 bg-red-500/10 rounded-lg border border-red-500/20">
            <span>🚨</span> {error}
          </div>
        ) : aiRecommendation ? (
          <div className="prose-container">
            <ReactMarkdown>{aiRecommendation}</ReactMarkdown>
          </div>
        ) : (
          <div className="text-gray-500 text-sm text-center p-8 bg-black/5 rounded-lg border border-dashed border-gray-300 dark:border-gray-700">
            No analysis generated yet. Click a server to start.
          </div>
        )}
      </div>

      {/* Utilization Score */}
      {analysis && (
        <div className="utilization-section">
          <div className="flex items-center justify-between mb-4">
            <h4 className="utilization-title">Resource utilization score</h4>
            <span className="utilization-value">{analysis.utilization_score.toFixed(1)}/100</span>
          </div>

          <div className="utilization-progress-bg">
            <div
              className="utilization-score-bar"
              style={{ width: `${analysis.utilization_score}%` }}
            />
          </div>

          <div className="utilization-footer">
            <p className="utilization-subtext">
              Estimated Waste: <span className="text-orange-500 font-semibold">{analysis.waste_percentage.toFixed(1)}%</span>
            </p>
            <p className="utilization-subtext">
              Monthly Loss: <span className="text-red-500 font-semibold">${analysis.monthly_waste.toFixed(2)}</span>
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default RecommendationsCard;
